"""
db_writer.py
============
Inserts a validated extraction dict (from the LLM pipeline) into the SQLite database.

Design
------
Every call to save_extraction() generates a brand-new unique meeting_id.
The LLM-suggested id from the JSON is intentionally discarded and replaced.

Why this matters:
- The LLM often produces the same id for meetings on the same date
  (e.g. "meet_2026_05_29") — using it directly would cause INSERT OR REPLACE
  to silently overwrite an existing meeting with the new one's data
- uuid4 guarantees a collision-free id on every single call, no matter how
  many meetings are uploaded on the same day

Child row IDs (task_001, dec_001 etc.) are generated sequentially at insert
time using an enumeration — they are NEVER taken from the LLM output.
Because the schema uses a composite PRIMARY KEY (id, meeting_id), the same
logical id (task_001) can exist in every meeting without any conflict.

Usage
-----
    from app.db.db_writer import save_extraction
    save_extraction(extraction_dict)  # returns meeting_id
"""
import logging
import sqlite3
import uuid
from datetime import date

from app.db.db_schema import get_connection, initialise_db

logger = logging.getLogger(__name__)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _csv(value) -> str | None:
    """Convert a list to a comma-separated string, or pass through strings."""
    if value is None:
        return None
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) if value else None
    return str(value)


def _new_meeting_id() -> str:
    """
    Generate a guaranteed-unique meeting ID.

    Format : meet_YYYY_MM_DD_<8 hex chars>
    Example: meet_2026_05_29_a3f7c1b8

    The date prefix makes IDs human-readable and naturally sortable.
    The hex suffix ensures uniqueness across multiple uploads on the same day.
    """
    today  = date.today().strftime("%Y_%m_%d")
    suffix = uuid.uuid4().hex[:8]
    return f"meet_{today}_{suffix}"


# ── Main writer ───────────────────────────────────────────────────────────────

def save_extraction(data: dict) -> str:
    """
    Insert all sections of a validated extraction dict into the database.

    Each upload always creates a completely new, isolated meeting record.
    Uploading the same transcript twice produces two separate meeting rows —
    the second never overwrites the first.

    How isolation works:
        1. A unique meeting_id is generated (uuid-based, never from the LLM)
        2. All child rows (tasks, blockers etc.) are stamped with that meeting_id
        3. Child IDs (task_001 etc.) are generated by enumeration, not from LLM
        4. Composite PKs (id, meeting_id) prevent any cross-meeting collision

    Args:
        data: Parsed extraction dict with keys:
              meeting, action_items, decisions, blockers, ambiguous.

    Returns:
        The meeting_id string that was actually stored.

    Raises:
        KeyError:          If required top-level keys are missing from data.
        sqlite3.Error:     If a database operation fails (transaction is rolled back).
    """
    # Ensure schema is present before writing
    initialise_db()

    meeting    = data["meeting"]
    meeting_id = _new_meeting_id()

    # Write back so callers (e.g. app.py) can read the actual stored id
    meeting["id"] = meeting_id

    conn = get_connection()
    try:
        # ── meetings ──────────────────────────────────────────────────────────
        # Plain INSERT — never INSERT OR REPLACE — so collisions surface loudly
        conn.execute(
            "INSERT INTO meetings (id, date, title) VALUES (?, ?, ?)",
            (meeting_id, meeting.get("date"), meeting.get("title")),
        )
        logger.info("Inserted new meeting: %s", meeting_id)

        # ── attendees ─────────────────────────────────────────────────────────
        attendees = meeting.get("attendees") or []
        for name in attendees:
            if name and name.strip():
                conn.execute(
                    "INSERT INTO attendees (meeting_id, name) VALUES (?, ?)",
                    (meeting_id, name.strip()),
                )
        logger.info("Inserted %d attendees for %s", len(attendees), meeting_id)

        # ── action_items ──────────────────────────────────────────────────────
        # IDs are generated here (task_001, task_002 ...) — never from the LLM
        # Composite PK (id, meeting_id) means task_001 can exist in every meeting
        action_items = data.get("action_items") or []
        for i, item in enumerate(action_items, start=1):
            item_id = f"task_{i:03d}"
            conn.execute(
                """
                INSERT INTO action_items
                    (id, meeting_id, title, owner, due_date,
                     priority, status, missing_fields, note)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    item_id,
                    meeting_id,
                    item.get("title"),
                    item.get("owner"),
                    item.get("due_date"),
                    item.get("priority"),
                    item.get("status"),
                    _csv(item.get("missing_fields")),
                    item.get("_note"),
                ),
            )
        logger.info("Inserted %d action items for %s", len(action_items), meeting_id)

        # ── decisions ─────────────────────────────────────────────────────────
        decisions = data.get("decisions") or []
        for i, item in enumerate(decisions, start=1):
            item_id = f"dec_{i:03d}"
            conn.execute(
                """
                INSERT INTO decisions
                    (id, meeting_id, decision, rationale,
                     status, missing_fields, note)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    item_id,
                    meeting_id,
                    item.get("decision"),
                    item.get("rationale"),
                    item.get("status"),
                    _csv(item.get("missing_fields")),
                    item.get("_note"),
                ),
            )
        logger.info("Inserted %d decisions for %s", len(decisions), meeting_id)

        # ── blockers ──────────────────────────────────────────────────────────
        blockers = data.get("blockers") or []
        for i, item in enumerate(blockers, start=1):
            item_id = f"blk_{i:03d}"
            conn.execute(
                """
                INSERT INTO blockers
                    (id, meeting_id, task, blocked_by,
                     owner, ticket, missing_fields)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    item_id,
                    meeting_id,
                    item.get("task"),
                    item.get("blocked_by"),
                    item.get("owner"),
                    item.get("ticket"),
                    _csv(item.get("missing_fields")),
                ),
            )
        logger.info("Inserted %d blockers for %s", len(blockers), meeting_id)

        # ── ambiguous ─────────────────────────────────────────────────────────
        ambiguous = data.get("ambiguous") or []
        for i, item in enumerate(ambiguous, start=1):
            item_id = f"amb_{i:03d}"
            conn.execute(
                """
                INSERT INTO ambiguous
                    (id, meeting_id, description, owner, note)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    item_id,
                    meeting_id,
                    item.get("description"),
                    item.get("owner"),
                    item.get("_note"),
                ),
            )
        logger.info("Inserted %d ambiguous items for %s", len(ambiguous), meeting_id)

        conn.commit()
        logger.info("All data committed for meeting %s", meeting_id)
        return meeting_id

    except (sqlite3.Error, KeyError) as e:
        conn.rollback()
        logger.error("DB write failed for %s — rolled back: %s", meeting_id, e)
        raise
    finally:
        conn.close()
